announce = false
debug = true
description = 'NemesusTV Tutorial Server'
gamemode = 'Roleplay'
host = '0.0.0.0'
language = 'de'
modules = [ 'js-module', 'csharp-module' ]
name = 'NemesusTV alt:V Server'
players = 15
port = 7788
resources = [ 'chat', 'AltVTutorial', 'AltVTutorialClientside', '19raptor' ]
website = 'nemesus.de'